[project]
name = "mcp-exploration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-anthropic>=0.3.0",
    "langchain>=0.3.8",
    "mcp>=1.0.0",
    "python-dotenv>=1.0.1",
    "langgraph>=0.2.53",
]
